//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServerShared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Urls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Urls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServerShared.Urls", typeof(Urls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44370/usuarioCallback.
        /// </summary>
        public static string ClientAngularCallback {
            get {
                return ResourceManager.GetString("ClientAngularCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientCredentiaisClientId.
        /// </summary>
        public static string ClientCredentiaisClientId {
            get {
                return ResourceManager.GetString("ClientCredentiaisClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientCredentiaisSecretSecret.
        /// </summary>
        public static string ClientCredentiaisSecret {
            get {
                return ResourceManager.GetString("ClientCredentiaisSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClienteCredentiaisClientIdCode.
        /// </summary>
        public static string ClienteCredentiaisClientIdCode {
            get {
                return ResourceManager.GetString("ClienteCredentiaisClientIdCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientImplicitClientId.
        /// </summary>
        public static string ClientImplicitClientId {
            get {
                return ResourceManager.GetString("ClientImplicitClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44357/usuarioCallback.
        /// </summary>
        public static string ClientMvc1CallBack {
            get {
                return ResourceManager.GetString("ClientMvc1CallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lgrup.com.br.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/.
        /// </summary>
        public static string STS {
            get {
                return ResourceManager.GetString("STS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/identity/connect/authorize.
        /// </summary>
        public static string STSAutorizeEndPoint {
            get {
                return ResourceManager.GetString("STSAutorizeEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/identity.
        /// </summary>
        public static string STSIdentity {
            get {
                return ResourceManager.GetString("STSIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/identity/connect/token.
        /// </summary>
        public static string STSTokenEndPoint {
            get {
                return ResourceManager.GetString("STSTokenEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44352/.
        /// </summary>
        public static string WebApi1 {
            get {
                return ResourceManager.GetString("WebApi1", resourceCulture);
            }
        }
    }
}
